spring:
  kafka:
    bootstrap-servers: kafka:29092

tracking:
  dynamodb:
    endpoint: http://dynamodb-local:8000
    create-table: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}
