spring:
  kafka:
    bootstrap-servers: kafka:29092
  datasource:
    url: jdbc:postgresql://postgres:5432/shipping_db

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

management.otlp.tracing.endpoint: ${OTLP_TRACING_ENDPOINT:http://jaeger:4318/v1/traces}
