spring:
  kafka:
    bootstrap-servers: kafka:29092

cart:
  dynamodb:
    endpoint: http://dynamodb-local:8000
    create-table: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}

management.otlp.tracing.endpoint: ${OTLP_TRACING_ENDPOINT:http://jaeger:4318/v1/traces}
